version: '1'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - network-app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb 
    depends_on:
      - db
    networks:
      - network-app
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - network-app

volumes:
  postgres_data:

networks:
  network-app:
    driver: bridge
